import type { CoevoSettings } from "./types";

export const defaults: CoevoSettings = {
  general: {
    default_home: "mission-chat",
    startup_behavior: "new-task",
    default_mission_mode: "auto",
    autosave_drafts: true,
    time_format: "24h",
    region: "auto",
  },
  appearance: {
    language: "en",
    theme: "system",
    font_size: "normal",
    density: "comfortable",
    sidebar_mode: "icon+text",
    reduce_motion: false,
    high_contrast: false,
  },
  model_provider: {
    provider: "openai-compatible",
    base_url: "https://api.openai.com/v1",
    api_key: "",
    default_model: "gpt-4o",
    fast_model: "gpt-4o-mini",
    reasoning_model: "o1",
    structured_output_model: "gpt-4o",
    max_tokens: 4096,
    temperature: 0.7,
    request_timeout_ms: 30000,
    max_cost_per_task_usd: 5.0,
  },
  agent_runtime: {
    default_agent_registry: "coevo-default",
    allow_task_agent_instance: true,
    allow_ephemeral_sub_agent: true,
    ephemeral_agent_ttl_minutes: 15,
    max_agents_per_task: 5,
    max_hops: 10,
    allow_cross_org_a2a: false,
    default_tool_scope: "urn:coevo:tool:*",
  },
  governance: {
    auto_confirm_green_track: true,
    yellow_approval_mode: "negative_consent",
    negative_consent_timeout_seconds: 300,
    red_requires_mfa: true,
    human_override_enabled: true,
    one_vote_blocker_roles: "CISO,SRE_Lead",
    responsibility_anchor_required: true,
  },
  risk_gate: {
    green_threshold: 0.3,
    yellow_threshold: 0.6,
    red_threshold: 0.8,
    action_risk_weight_blast_radius: 0.30,
    action_risk_weight_irreversibility: 0.35,
    inaction_risk_weight_service_impact: 0.40,
    emergency_lease_enabled: true,
    default_lease_duration_seconds: 900,
    default_lease_budget: 3,
    require_dual_sign_for_emergency: true,
  },
  cognitive_customs: {
    default_fact_ttl_seconds: 3600,
    require_provenance_for_fact: true,
    allow_hypothesis_auto_promotion: false,
    fact_promotion_evidence_level: "unit_tests_passing",
    revoked_fact_invalidation_strategy: "transitive",
    replay_mode_blocks_fact_write: true,
  },
  policy_engine: {
    policy_engine: "opa",
    policy_bundle_path: "",
    policy_version: "0".repeat(64),
    decision_log_enabled: true,
    policy_simulation_enabled: false,
    policy_diff_enabled: true,
    health_check_url: "",
  },
  privacy: {
    log_retention_days: 30,
    store_full_prompts: false,
    store_model_outputs: false,
    pii_redaction_enabled: true,
    local_database_path: "data/coevo.db",
  },
  developer: {
    api_base_url: "http://127.0.0.1:8717",
    openapi_url: "http://127.0.0.1:8717/openapi.json",
    debug_logs_enabled: false,
    show_traceparent: false,
    show_raw_json_panels: false,
    feature_flags: "",
  },
};
